FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

RUN echo "fs.inotify.max_user_watches=524288" >> /etc/sysctl.conf || true

EXPOSE 3000

CMD ["sh", "-c", "npm run migration:run:prod && npm run start:dev"]